services:
  - type: web
    name: namu-blog-backend
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    rootDir: backend
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: namu_blog
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@namu.sa
      - key: ADMIN_PASSWORD
        value: Admin@2026
      - key: ADMIN_SIGNUP_CODE
        value: NAMU-56-TMJVTKQZK3Y
      - key: FRONTEND_URL
        sync: false
      - key: CORS_ORIGINS
        sync: false
