// Sample showcase articles shown when backend is offline
// This ensures the blog always looks complete and professional for visitors.
export const SAMPLE_ARTICLES = [
  {
    id: "sample-1",
    title: "رحلة معلمة بين الفصل والتميز",
    content:
      "تتعدد الأدوار التي تقوم بها المعلمة في الفصل، فهي ليست مجرد ناقلة للمعرفة، بل مربيةٌ ومرشدةٌ وقائدة. في هذه الرحلة، أشاركك أبرز الدروس التي تعلمتها من طالباتي خلال سنواتي في الميدان، وكيف صنعت كل تجربة منهنّ بصمةً في وعيي المهني.\n\nأهم ما تعلمته: أن الإصغاء أعمق من السؤال، وأن الكلمة الطيبة في وقتها قد تُغيِّر مسار طالبة كاملاً.",
    category: "تربوية",
    author_id: "showcase",
    author_name: "هيئة التحرير",
    images: [],
    links: [],
    likes_count: 24,
    comments_count: 7,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    is_liked: false,
  },
  {
    id: "sample-2",
    title: "استراتيجيات التعلم النشط في الفصل الحديث",
    content:
      "التعلم النشط ليس مجرد نشاط داخل الفصل، بل فلسفة كاملة تجعل الطالبة محوراً للعملية التعليمية. في هذا المقال أستعرض ثلاث استراتيجيات جربتها بنفسي: التعلم بالأقران، خرائط المفاهيم التعاونية، والمشاريع البحثية الصغيرة.\n\nنتائج التطبيق كانت مذهلة — ارتفاع ملحوظ في تفاعل الطالبات، وتحسن واضح في الفهم العميق للمادة.",
    category: "تعليمية",
    author_id: "showcase",
    author_name: "هيئة التحرير",
    images: [],
    links: [],
    likes_count: 31,
    comments_count: 12,
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    is_liked: false,
  },
  {
    id: "sample-3",
    title: "كيف أبني علاقة إيجابية مع طالباتي؟",
    content:
      "العلاقة بين المعلمة وطالباتها هي حجر الأساس لأي تعلّم حقيقي. في تجربتي، اكتشفت أن الاحترام المتبادل والاهتمام الحقيقي بشخصية كل طالبة، يفتح أبواباً لا تفتحها أعتى الاستراتيجيات.\n\nخمس نصائح عملية: التحية اليومية بالاسم، ذكر إنجاز صغير لكل طالبة كل أسبوع، الإصغاء الفعّال، تقبّل الاختلاف، وأن نكون قدوة قبل أن نطلب من غيرنا.",
    category: "تحفيزية",
    author_id: "showcase",
    author_name: "هيئة التحرير",
    images: [],
    links: [],
    likes_count: 18,
    comments_count: 4,
    created_at: new Date(Date.now() - 86400000 * 8).toISOString(),
    is_liked: false,
  },
  {
    id: "sample-4",
    title: "أدوات تقنية ترتقي بفصلك",
    content:
      "في عصرٍ تحاصره الشاشات، يصبح توظيف التقنية لخدمة التعلم ضرورة لا ترفاً. أشارككنّ أربع أدوات مجانية أحببتها واستخدمتها: Quizlet للحفظ، Padlet للنقاش، Canva للعروض، وKahoot للاختبارات التفاعلية.\n\nكلها تحتاج خمس دقائق فقط لتعلّمها، وتُحدث أثراً واضحاً في تفاعل الطالبات.",
    category: "تقنية",
    author_id: "showcase",
    author_name: "هيئة التحرير",
    images: [],
    links: [],
    likes_count: 27,
    comments_count: 9,
    created_at: new Date(Date.now() - 86400000 * 12).toISOString(),
    is_liked: false,
  },
  {
    id: "sample-5",
    title: "صوت المعلمة: قوة في صياغة الجيل",
    content:
      "صوت المعلمة لا يُقاس بشدّته، بل بأثره. كم من كلمة عابرة من معلمة، صنعت طبيبة، أو مهندسة، أو قائدة. في هذا المقال أتأمل في رسالتنا، وأذكّر نفسي وأخواتي بعِظَم ما نحمل من أمانة.\n\nقد لا نرى الثمرة اليوم، لكن البذرة التي نزرعها في كل فصل، ستُورق غداً في أمة بأسرها.",
    category: "تحفيزية",
    author_id: "showcase",
    author_name: "هيئة التحرير",
    images: [],
    links: [],
    likes_count: 42,
    comments_count: 15,
    created_at: new Date(Date.now() - 86400000 * 16).toISOString(),
    is_liked: false,
  },
  {
    id: "sample-6",
    title: "إدارة الفصل: فنٌّ يتعلّم",
    content:
      "إدارة الفصل ليست سلطة، بل ائتلاف. كيف ندير 30 طالبة بشخصيات متباينة دون أن نُرهق أنفسنا؟ في هذا المقال أشارككنّ خبرتي في وضع قواعد الفصل بشكل تشاركي، وإدارة الوقت بذكاء، والتعامل مع المواقف الصعبة بهدوء.",
    category: "إدارية",
    author_id: "showcase",
    author_name: "هيئة التحرير",
    images: [],
    links: [],
    likes_count: 19,
    comments_count: 6,
    created_at: new Date(Date.now() - 86400000 * 20).toISOString(),
    is_liked: false,
  },
];
